name: 'Install Luau'
description: 'Installs Luau for use in Github Actions'

inputs:
  verbose:
    description: Debug Logging
    required: false
    default: "false"
  version:
    description: Pinned version
    required: false
    default: "latest"

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'