name: Unit Tests

on: [push, pull_request, workflow_dispatch]

jobs:
    run_tests:
        name: Test Action
        strategy:
            matrix:
                os: ["windows-latest", "macos-latest", "ubuntu-latest"]
                verbose: ["true", "false"]
        
        runs-on: ${{ matrix.os }}
        timeout-minutes: 2

        steps:
          - name: Checkout Project
            uses: actions/checkout@v4

          - name: Install
            uses: encodedvenom/install-luau@debug
            with:
                verbose: ${{ matrix.verbose }}

          - name: Hello World
            shell: bash
            run: |
                if ${{ runner.os == 'Windows' }}; then
                    luau.exe tests/hello_world.luau 
                else
                    luau tests/hello_world.luau
                fi