name: Unit Tests

on: [push, pull_request, workflow_dispatch]

jobs:
    run_win:
        name: Run Windows
        runs-on: windows-latest
        timeout-minutes: 2

        steps:
          - name: Checkout Project
            uses: actions/checkout@v4

          - name: Install
            uses: encodedvenom/install-luau@debug

          - name: Hello World
            run: luau.exe tests/hello_world.luau 

    job_macos:
        name: Run Mac
        runs-on: macos-latest
        timeout-minutes: 2

        steps:
          - name: Checkout Project
            uses: actions/checkout@v4

          - name: Install
            uses: encodedvenom/install-luau@debug

          - name: Hello World
            run: luau tests/hello_world.luau 

    job_ubuntu:
        name: Run Ubuntu
        runs-on: ubuntu-latest
        timeout-minutes: 2

        steps:
          - name: Checkout Project
            uses: actions/checkout@v4

          - name: Install
            uses: encodedvenom/install-luau@debug

          - name: Hello World
            run: luau tests/hello_world.luau 